import { Geist, Geist_Mono } from "next/font/google";
import ReduxProvider from "../../redux";
import "react-datepicker/dist/react-datepicker.css";
import "./globals.css";
import Header from "@/shares/AdminHeader";
import Sidebar from "@/shares/AdminSidebar";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dev Setu",
  description: "Generated by Dev Setu",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <ReduxProvider>
          <Header />
          <div className="flex">
            <Sidebar />
             <>
               {children}
             </>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
