export const ARTICLES_DATA_REQUEST = "ARTICLES_DATA_REQUEST"
export const ARTICLES_DATA_RESPONSE = "ARTICLES_DATA_RESPONSE"
export const ARTICLES_DATA_FAILED = "ARTICLES_DATA_FAILED"

export const ADD_NEW_ARTICLES_DATA_REQUEST = "ADD_NEW_ARTICLES_DATA_REQUEST"
export const ADD_NEW_ARTICLES_DATA_RESPONSE = "ADD_NEW_ARTICLES_DATA_RESPONSE"
export const ADD_NEW_ARTICLES_DATA_FAILED = "ADD_NEW_ARTICLES_DATA_FAILED"

export const ARTICLES_DETAILS_DATA_REQUEST = "ARTICLES_DETAILS_DATA_REQUEST"
export const ARTICLES_DETAILS_DATA_RESPONSE = "ARTICLES_DETAILS_DATA_RESPONSE"
export const ARTICLES_DETAILS_DATA_FAILED = "ARTICLES_DETAILS_DATA_FAILED"

export const DELETE_ARTICLES_DATA_REQUEST = "DELETE_ARTICLES_DATA_REQUEST"
export const DELETE_ARTICLES_DATA_RESPONSE = "DELETE_ARTICLES_DATA_RESPONSE"
export const DELETE_ARTICLES_DATA_FAILED = "DELETE_ARTICLES_DATA_FAILED"

export const UPDATE_ARTICLES_DATA_REQUEST = "UPDATE_ARTICLES_DATA_REQUEST"
export const UPDATE_ARTICLES_DATA_RESPONSE = "UPDATE_ARTICLES_DATA_RESPONSE"
export const UPDATE_ARTICLES_DATA_FAILED = "UPDATE_ARTICLES_DATA_FAILED"