// CART TYPES

export const CART_DATA_REQUEST = "CART_DATA_REQUEST";
export const CART_DATA_RESPONSE = "CART_DATA_RESPONSE";
export const CART_DATA_FAILED = "CART_DATA_FAILED";

export const ADD_NEW_CART_REQUEST = "ADD_NEW_CART_REQUEST";
export const ADD_NEW_CART_RESPONSE = "ADD_NEW_CART_RESPONSE";
export const ADD_NEW_CART_FAILED = "ADD_NEW_CART_FAILED";

export const UPDATE_CART_REQUEST = "UPDATE_CART_REQUEST";
export const UPDATE_CART_RESPONSE = "UPDATE_CART_RESPONSE";
export const UPDATE_CART_FAILED = "UPDATE_CART_FAILED";

export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST";

export const REMOVE_FROM_CART_RESPONSE = "REMOVE_FROM_CART_RESPONSE";
export const REMOVE_FROM_CART_FAILED = "REMOVE_FROM_CART_FAILED";

export const CART_DETAILS_REQUEST = "CART_DETAILS_REQUEST";
export const CART_DETAILS_RESPONSE = "CART_DETAILS_RESPONSE";
export const CART_DETAILS_FAILED = "CART_DETAILS_FAILED";


export const ADD_PACKAGE_REQUEST = "ADD_PACKAGE_REQUEST";

export const REMOVE_PACKAGE_REQUEST = "REMOVE_PACKAGE_REQUEST";

export const ADD_OFFERING_REQUEST = "ADD_OFFERING_REQUEST";

export const UPDATE_OFFERING_COUNT_REQUEST = "UPDATE_OFFERING_COUNT_REQUEST";

export const CLEAR_CART = "CLEAR_CART";

