export const CHADHAVA_DATA_REQUEST = "CHADHAVA_DATA_REQUEST"
export const CHADHAVA_DATA_RESPONSE = "CHADHAVA_DATA_RESPONSE"
export const CHADHAVA_DATA_FAILED = "CHADHAVA_DATA_FAILED"

export const ADD_NEW_CHADHAVA_DATA_REQUEST = "ADD_NEW_CHADHAVA_DATA_REQUEST"
export const ADD_NEW_CHADHAVA_DATA_RESPONSE = "ADD_NEW_CHADHAVA_DATA_RESPONSE"
export const ADD_NEW_CHADHAVA_DATA_FAILED = "ADD_NEW_CHADHAVA_DATA_FAILED"

export const CHADHAVA_DETAILS_DATA_REQUEST = "CHADHAVA_DETAILS_DATA_REQUEST"
export const CHADHAVA_DETAILS_DATA_RESPONSE = "CHADHAVA_DETAILS_DATA_RESPONSE"
export const CHADHAVA_DETAILS_DATA_FAILED = "CHADHAVA_DETAILS_DATA_FAILED"

export const DELETE_CHADHAVA_DATA_REQUEST = "DELETE_CHADHAVA_DATA_REQUEST"
export const DELETE_CHADHAVA_DATA_RESPONSE = "DELETE_CHADHAVA_DATA_RESPONSE"
export const DELETE_CHADHAVA_DATA_FAILED = "DELETE_CHADHAVA_DATA_FAILED"

export const UPDATE_CHADHAVA_DATA_REQUEST = "UPDATE_CHADHAVA_DATA_REQUEST"
export const UPDATE_CHADHAVA_DATA_RESPONSE = "UPDATE_CHADHAVA_DATA_RESPONSE"
export const UPDATE_CHADHAVA_DATA_FAILED = "UPDATE_CHADHAVA_DATA_FAILED"