export const FAQS_DATA_REQUEST = "FAQS_DATA_REQUEST"
export const FAQS_DATA_RESPONSE = "FAQS_DATA_RESPONSE"
export const FAQS_DATA_FAILED = "FAQS_DATA_FAILED"

export const ADD_NEW_FAQS_DATA_REQUEST = "ADD_NEW_FAQS_DATA_REQUEST"
export const ADD_NEW_FAQS_DATA_RESPONSE = "ADD_NEW_FAQS_DATA_RESPONSE"
export const ADD_NEW_FAQS_DATA_FAILED = "ADD_NEW_FAQS_DATA_FAILED"

export const FAQS_DETAILS_DATA_REQUEST = "FAQS_DETAILS_DATA_REQUEST"
export const FAQS_DETAILS_DATA_RESPONSE = "FAQS_DETAILS_DATA_RESPONSE"
export const FAQS_DETAILS_DATA_FAILED = "FAQS_DETAILS_DATA_FAILED"

export const DELETE_FAQS_DATA_REQUEST = "DELETE_FAQS_DATA_REQUEST"
export const DELETE_FAQS_DATA_RESPONSE = "DELETE_FAQS_DATA_RESPONSE"
export const DELETE_FAQS_DATA_FAILED = "DELETE_FAQS_DATA_FAILED"

export const UPDATE_FAQS_DATA_REQUEST = "UPDATE_FAQS_DATA_REQUEST"
export const UPDATE_FAQS_DATA_RESPONSE = "UPDATE_FAQS_DATA_RESPONSE"
export const UPDATE_FAQS_DATA_FAILED = "UPDATE_FAQS_DATA_FAILED"