export const HOME_DATA_REQUEST = "HOME_DATA_REQUEST"
export const HOME_DATA_RESPONSE = "HOME_DATA_RESPONSE"
export const HOME_DATA_FAILED = "HOME_DATA_FAILED"

// export const ADD_NEW_PUJA_DATA_REQUEST = "ADD_NEW_PUJA_DATA_REQUEST"
// export const ADD_NEW_PUJA_DATA_RESPONSE = "ADD_NEW_PUJA_DATA_RESPONSE"
// export const ADD_NEW_PUJA_DATA_FAILED = "ADD_NEW_PUJA_DATA_FAILED"

// export const PUJA_DETAILS_DATA_REQUEST = "PUJA_DETAILS_DATA_REQUEST"
// export const PUJA_DETAILS_DATA_RESPONSE = "PUJA_DETAILS_DATA_RESPONSE"
// export const PUJA_DETAILS_DATA_FAILED = "PUJA_DETAILS_DATA_FAILED"

// export const DELETE_PUJA_DATA_REQUEST = "DELETE_PUJA_DATA_REQUEST"
// export const DELETE_PUJA_DATA_RESPONSE = "DELETE_PUJA_DATA_RESPONSE"
// export const DELETE_PUJA_DATA_FAILED = "DELETE_PUJA_DATA_FAILED"

// export const UPDATE_PUJA_DATA_REQUEST = "UPDATE_PUJA_DATA_REQUEST"
// export const UPDATE_PUJA_DATA_RESPONSE = "UPDATE_PUJA_DATA_RESPONSE"
// export const UPDATE_PUJA_DATA_FAILED = "UPDATE_PUJA_DATA_FAILED"