export const OFFERINGS_DATA_REQUEST = "OFFERINGS_DATA_REQUEST"
export const OFFERINGS_DATA_RESPONSE = "OFFERINGS_DATA_RESPONSE"
export const OFFERINGS_DATA_FAILED = "OFFERINGS_DATA_FAILED"

export const ADD_NEW_OFFERINGS_DATA_REQUEST = "ADD_NEW_OFFERINGS_DATA_REQUEST"
export const ADD_NEW_OFFERINGS_DATA_RESPONSE = "ADD_NEW_OFFERINGS_DATA_RESPONSE"
export const ADD_NEW_OFFERINGS_DATA_FAILED = "ADD_NEW_OFFERINGS_DATA_FAILED"

export const OFFERINGS_DETAILS_DATA_REQUEST = "OFFERINGS_DETAILS_DATA_REQUEST"
export const OFFERINGS_DETAILS_DATA_RESPONSE = "OFFERINGS_DETAILS_DATA_RESPONSE"
export const OFFERINGS_DETAILS_DATA_FAILED = "OFFERINGS_DETAILS_DATA_FAILED"

export const DELETE_OFFERINGS_DATA_REQUEST = "DELETE_OFFERINGS_DATA_REQUEST"
export const DELETE_OFFERINGS_DATA_RESPONSE = "DELETE_OFFERINGS_DATA_RESPONSE"
export const DELETE_OFFERINGS_DATA_FAILED = "DELETE_OFFERINGS_DATA_FAILED"

export const UPDATE_OFFERINGS_DATA_REQUEST = "UPDATE_OFFERINGS_DATA_REQUEST"
export const UPDATE_OFFERINGS_DATA_RESPONSE = "UPDATE_OFFERINGS_DATA_RESPONSE"
export const UPDATE_OFFERINGS_DATA_FAILED = "UPDATE_OFFERINGS_DATA_FAILED"