export const PACKAGE_DATA_REQUEST = "PACKAGE_DATA_REQUEST"
export const PACKAGE_DATA_RESPONSE = "PACKAGE_DATA_RESPONSE"
export const PACKAGE_DATA_FAILED = "PACKAGE_DATA_FAILED"

export const ADD_NEW_PACKAGE_DATA_REQUEST = "ADD_NEW_PACKAGE_DATA_REQUEST"
export const ADD_NEW_PACKAGE_DATA_RESPONSE = "ADD_NEW_PACKAGE_DATA_RESPONSE"
export const ADD_NEW_PACKAGE_DATA_FAILED = "ADD_NEW_PACKAGE_DATA_FAILED"

export const PACKAGE_DETAILS_DATA_REQUEST = "PACKAGE_DETAILS_DATA_REQUEST"
export const PACKAGE_DETAILS_DATA_RESPONSE = "PACKAGE_DETAILS_DATA_RESPONSE"
export const PACKAGE_DETAILS_DATA_FAILED = "PACKAGE_DETAILS_DATA_FAILED"

export const DELETE_PACKAGE_DATA_REQUEST = "DELETE_PACKAGE_DATA_REQUEST"
export const DELETE_PACKAGE_DATA_RESPONSE = "DELETE_PACKAGE_DATA_RESPONSE"
export const DELETE_PACKAGE_DATA_FAILED = "DELETE_PACKAGE_DATA_FAILED"

export const UPDATE_PACKAGE_DATA_REQUEST = "UPDATE_PACKAGE_DATA_REQUEST"
export const UPDATE_PACKAGE_DATA_RESPONSE = "UPDATE_PACKAGE_DATA_RESPONSE"
export const UPDATE_PACKAGE_DATA_FAILED = "UPDATE_PACKAGE_DATA_FAILED"