export const PAYMENT_OREDR_REQUEST = "PAYMENT_OREDR_REQUEST"
export const PAYMENT_OREDR_RESPONSE = "PAYMENT_OREDR_RESPONSE"
export const PAYMENT_OREDR_FAILED = "PAYMENT_OREDR_FAILED"

export const PAYMENT_OREDR_VERIFY_REQUEST = "PAYMENT_OREDR_VERIFY_REQUEST"
export const PAYMENT_OREDR_VERIFY_RESPONSE = "PAYMENT_OREDR_VERIFY_RESPONSE"
export const PAYMENT_OREDR_VERIFY_FAILED = "PAYMENT_OREDR_VERIFY_FAILED"
