export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_RESPONSE = "USER_DETAILS_RESPONSE"
export const USER_DETAILS_FAILED = "USER_DETAILS_FAILED"

export const ADD_NEW_USER_DETAILS_REQUEST = "ADD_NEW_USER_DETAILS_REQUEST"
export const ADD_NEW_USER_DETAILS_RESPONSE = "ADD_NEW_USER_DETAILS_RESPONSE"
export const ADD_NEW_USER_DETAILS_FAILED = "ADD_NEW_USER_DETAILS_FAILED"
