export const USER_REGISTRATION_REQUEST = "USER_REGISTRATION_REQUEST"
export const USER_REGISTRATION_RESPONSE = "USER_REGISTRATION_RESPONSE"
export const USER_REGISTRATION_FAILED = "USER_REGISTRATION_FAILED"

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_RESPONSE = "USER_LOGIN_RESPONSE"
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED"


export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST"