// src/app/(main)/layout.js

import { Roboto } from "next/font/google";
import "react-datepicker/dist/react-datepicker.css";
import ReduxProvider from "@/redux";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "../globals.css";
import { LangProvider } from "../langProviders";
import Header from "@/shares/Header";
import Footer from "@/shares/Footer";


// Roboto
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Dev Setu",
  description: "Generated by Dev Setu",
};

export default function RootLayout({ children, mainClass }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}
      >
        <ReduxProvider>
          <LangProvider>
            <Header />
              {children}
            <Footer />
          </LangProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
